### ISSUE TITLE
method for running rstudio in podman

### ISSUE THREAD

**Issue by e3bo** [nuest/rodman#1]
I seem to have gotten rocker/rstudio to work with podman on Arch Linux by making a few small changes. Here is my command line

     podman run -p 8789:8787 -e DISABLE_AUTH=true --rm -it docker.io/eamon/rstudio-nopriv:latest bash -c /init

Invoking `/init` via bash seems to eliminate the error about `/run`. After doing that, another error occurs later on when Rstudio server tries to increase the number of files it can open. I believe this is because my user does not have the associated capability for changing that. But I noticed the limit on my system was already much higher than what Rstudio wanted, so I simply commented out that line of code in the Rstudio sources, rebuilt the deb package, and then rebuilt the rocker/rstudio image with this modified Rstudio.

I'd be interested to hear if this approach may be improved on somehow (or is way off the mark), and also any insight into why invoking `/init` via bash seems to be important.

**Comment by nuest** [comment]
Thanks @e3bo for reporting this! I was totally swamped last autumn.

I have no idea about the bash vs. `/init` problem, I'm afraid.

Would you be willing to open a PR to update the README with what you learned?

**Comment by e3bo** [comment]
Sure thing @nuest! I should get to it sometime next week.

**Comment by e3bo** [comment]
I'm happy to report that my former convoluted solution no longer seems necessary. The proposed solution on the updated README of 

    podman run -dit --ulimit="nofile=4096" --env PASSWORD=bioc -p 8789:8787 --name rocker docker.io/rocker/rstudio

works on my system. The `--ulimit` setting eliminates the need to patch and rebuild RStudio as I did before. My guess is that updates to podman have eliminated the need to add `bash -c /init` to the command line. I think users interested in using podman would do best to use a recent version. I have had success with podman version 1.6.2 on Ubuntu 19.10 and podman version 1.7.0 on a recently updated Arch Linux system.
